// ────── ╔╗
// ╔═╦╦═╦╦╬╣ Exceptions.cs
// ║║║║╬║╔╣║ Various exception types used for Nori
// ╚╩═╩═╩╝╚╝ ───────────────────────────────────────────────────────────────────────────────────────
namespace Nori;

#region class AuException --------------------------------------------------------------------------
/// <summary>Exceptions generated by the Au serialization system</summary>
public sealed class AuException (string message) : Exception (message);
#endregion

#region class BadCaseException ---------------------------------------------------------------------
/// <summary>Thrown when a case is not handled in some switch statement</summary>
/// This is typically a sign of unfinished code
public class BadCaseException (object e, [CallerMemberName] string? caller = null) : Exception ($"Unhandled case '{e}' in {caller}");
#endregion

#region class IncompleteCodeException --------------------------------------------------------------
/// <summary>Signals that some code is incomplete (some cases not handled, for example)</summary>
public class IncompleteCodeException (string text) : Exception ($"Incomplete code: {text}");
#endregion

#region class ParseException -----------------------------------------------------------------------
/// <summary>Thrown when we are not able to parse a string to a particular type</summary>
public class ParseException : Exception {
   public ParseException (string value, Type type) : base ($"Cannot convert '{value}' to {Lib.NiceName (type)}") { }
   public ParseException (string text) : base (text) { }
}
#endregion
