// ────── ╔╗
// ╔═╦╦═╦╦╬╣ Globals.cs
// ║║║║╬║╔╣║ <<TODO>>
// ╚╩═╩═╩╝╚╝ ───────────────────────────────────────────────────────────────────────────────────────
global using System;
global using System.IO;
global using System.Text;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reactive;
global using System.Reactive.Linq;
