<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutDir>..\..\Bin</OutDir>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\UXDemo\InlayCompile.cs" Link="InlayCompile.cs" />
    <Compile Include="..\UXDemo\InlayGen.cs" Link="InlayGen.cs" />
    <Compile Include="..\UXDemo\InlayHub.cs" Link="InlayHub.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Nori.Core.csproj" />
    <ProjectReference Include="..\..\UX\Nori.UX.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
	</ItemGroup>

</Project>
