// ────── ╔╗
// ╔═╦╦═╦╦╬╣ Globals.cs
// ║║║║╬║╔╣║ <<TODO>>
// ╚╩═╩═╩╝╚╝ ───────────────────────────────────────────────────────────────────────────────────────
global using System;
global using System.IO;
global using System.Linq;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Xml.Linq;
global using System.Reflection;
global using System.Text;
